# Handling Numerical Data

In [1]:
import numpy as np


In [2]:
from sklearn import preprocessing

In [3]:
feature = np.array([[-500.5],[-100.1],[0],[100.1],[900.9]])

In [4]:
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))

In [5]:
scaled_feature = minmax_scale.fit_transform(feature)

In [6]:
scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

# Standardizing a Feature

In [7]:
import numpy as np 
from sklearn import preprocessing

In [8]:
x = np.array([[-1000.1],[-200.2],[500.5],[600.6],[9000.9]])

In [9]:
scaler = preprocessing.StandardScaler()

In [13]:
standardized = scaler.fit_transform(x)

In [14]:
standardized

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [15]:
# print mean and standard deviation

print("Mean:", round(standardized.mean()))

print("Standard Deviation:", standardized.std())

Mean: 0.0
Standard Deviation: 1.0


In [16]:
robust_scaler = preprocessing.RobustScaler()

In [17]:
robust_scaler.fit_transform(x)

array([[-1.87387612],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])