# Vectors and Matrices
In this chapter we will go through the operations in the Vectors and Matrices. 

# Vector

In [129]:
# loading library
import numpy as np

In [127]:
# Create a row vector
vector_row = np.array([1,2,3])

In [128]:
# Create a column vector
vector_column = np.array([[1],[2],[3]])

# Matrix

In [1]:
# Load library
import numpy as np

In [2]:
# create a matrix
matrix = np.array([[1,2],[1,2],[1,2]])

# Sparse Matrix

In [3]:
import numpy as numpy
from scipy import sparse

In [4]:
matrix = np.array([[0, 0], [0,1], [3,0]])

In [5]:
matrix_sparse = sparse.csr_matrix(matrix)

In [6]:
print(matrix_sparse)

(1, 1)	1
  (2, 0)	3


In [7]:
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0,0,0, 0],[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],[3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [8]:
matrix_large_sparse = sparse.csr_matrix (matrix_large)

In [9]:
print(matrix_large_sparse)

(1, 1)	1
  (2, 0)	3


# Selecting Elements

In [10]:
import numpy as np

In [11]:
vector = np.array([1,2,3,4,5,6])

In [12]:
matrix = np.array([[1,2,3],[4,5,6]])

In [13]:
vector [2]

3

In [14]:
matrix [1,1]

5

In [15]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [16]:
vector[:3]

array([1, 2, 3])

In [17]:
vector[3:]

array([4, 5, 6])

In [18]:
vector[-1]

6

In [19]:
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
matrix[:, 1:2]

array([[2],
       [5]])

# Describing a matrix

In [21]:
import numpy as np

In [22]:
matrix = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [23]:
matrix.shape

(3, 4)

In [24]:
matrix.size

12

In [25]:
matrix.ndim

2

# Applying Operations to Elements

In [26]:
import numpy as np

In [27]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [28]:
add_100 = lambda i:i + 100

In [29]:
vectorised_add_100 = np.vectorize(add_100)

In [30]:
vectorised_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

# Finding the Maximum and Minimum Values

In [31]:
import numpy as np

In [32]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
np.max(matrix)

9

In [34]:
np.min(matrix)

1

In [35]:
np.max(matrix, axis=0)

array([7, 8, 9])

In [36]:
np.min(matrix, axis=1)

array([1, 4, 7])

# Calculating Average, Variance and Standard Deviation

In [37]:
import numpy as np

In [38]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
np.mean(matrix)

5.0

In [40]:
np.var(matrix)

6.666666666666667

In [41]:
np.std(matrix)

2.581988897471611

In [42]:
np.mean(matrix, axis=0)

array([4., 5., 6.])

Just like max and min, we can easily get descriptive statistics about the whole matrix or do calculations along a single axis:

# Reshaping Arrays

In [43]:
matrix = matrix
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [48]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [51]:
matrix.size

12

In [52]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [53]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Transposing a Vector or Matrix

In [55]:
import numpy as np

In [59]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [60]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [62]:
# transpose vector
np.array([1,2,3,4,5,6]).T

array([1, 2, 3, 4, 5, 6])

In [63]:
# transpose row vector
np.array([[1,2,3,4,5,6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Flattening a Matrix

In [64]:
import numpy as np

In [65]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Finding the Rank of a Matrix

In [70]:
import numpy as np

In [71]:
matrix = np.array([[1,1,1],[1,1,10],[1,1,15]])

In [72]:
np.linalg.matrix_rank(matrix)

2

In [73]:
np.linalg.matrix_rank(matrix_large)

2

In [74]:
matrix_large

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [75]:
np.linalg.matrix_rank(matrix_large_sparse)

1

# Calculating the Determinant

In [76]:
matrix = np.array([[1,2,3],[2,4,6],[3,8,9]])

In [77]:
np.linalg.det(matrix)

0.0

# Getting the Diagonal of a Matrix

In [82]:
matrix = np.array([[1,2,3],[2,4,6],[3,8,9]])

In [83]:
matrix.diagonal()

array([1, 4, 9])

In [84]:
matrix.diagonal(offset = 1)

array([2, 6])

In [86]:
matrix.diagonal(offset=-1)

array([2, 8])

In [87]:
matrix.diagonal(offset=2)

array([3])

# Calculate the Trase of a Matrix

In [88]:
matrix = np.array([[1,2,3],[2,4,6],[3,8,9]])

In [89]:
matrix.trace()

14

In [90]:
sum(matrix.diagonal())

14

# Finding Eigenvalues and Eigenvectors

In [92]:
import numpy as numpy

In [93]:
matrix = np.array([[1,-1,3],[1,1,6],[3,8,9]])

In [94]:
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [95]:
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [96]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

# Calculating Dot Products

In [99]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

In [100]:
np.dot(vector_a, vector_b)

32

In [101]:
vector_a @ vector_b

32

# Adding and Subtracting Matrices

In [104]:
matrix_a = np.array([[1,1,1],[1,1,1],[1,1,2]])
matrix_b = np.array([[1,3,1],[1,3,1],[1,3,8]])

In [105]:
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [106]:
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [107]:
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

# Multiplying Matrices

In [109]:
matrix_a = np.array([[1,1],[1,2]])

In [110]:
matrix_b = np.array([[1,3],[1,2]])

In [111]:
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [112]:
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [113]:
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

# Inverting a Matrix

In [114]:
matrix = np.array([[1,4],[2,5]])

In [115]:
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [116]:
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

# Generating Random Values

In [118]:
np.random.seed(0)

In [119]:
# Generate three random floats between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [120]:
# Generate three random integers between 1 and 10
np.random.randint(0,11,3)

array([3, 7, 9])

In [121]:
# Draw three random integers distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0,1.0,3)

array([-1.42232584,  1.52006949, -0.29139398])

In [122]:
np.random.logistic(0.0,1.0,3)
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0

array([-0.98118713, -0.08939902,  1.46416405])

In [123]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0,2.0,3)

array([1.47997717, 1.3927848 , 1.83607876])